create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;

drop policy if exists "Anyone can read projects" on public.projects;
create policy "Anyone can read projects"
on public.projects for select
to anon
using (true);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 5 and 255),
  message text not null check (char_length(message) between 2 and 5000),
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Anyone can send contact messages" on public.contact_messages;
create policy "Anyone can send contact messages"
on public.contact_messages for insert
to anon
with check (true);

insert into public.projects (title, category, description)
select * from (values
  ('Nền tảng học tập', 'Product Design', 'Thiết kế trải nghiệm học tập rõ ràng và dễ tiếp cận cho mọi người.'),
  ('Ví cá nhân', 'UX / UI', 'Giúp người dùng hiểu và chủ động hơn với thói quen tài chính của mình.'),
  ('Bộ nhận diện Mộc', 'Brand Direction', 'Xây dựng tiếng nói hình ảnh mộc mạc, hiện đại cho một thương hiệu địa phương.')
) as seed(title, category, description)
where not exists (select 1 from public.projects);
